import type { Pool, RowDataPacket } from "mysql2/promise";
import { toMysqlDate } from "./json.js";

export type PackageCacheStatus = "missing" | "downloading" | "ready" | "stale" | "deleting" | "delete_failed";
export interface PackageCacheRecord { cacheId:number; cacheKey:string; dramaId:string; packageTaskId?:string; packageObjectKey?:string; packageName:string; deviceId:string; zipPath?:string; extractPath?:string; zipExists:boolean; extracted:boolean; episodeCount?:number; sizeBytes:number; status:PackageCacheStatus; lastUsedAt?:string; lastError?:string; createdAt:string; updatedAt:string; }
interface CacheRow extends RowDataPacket { cache_id:number; cache_key:string; drama_id:string; package_task_id:string|null; package_object_key:string|null; package_name:string; device_id:string; zip_path:string|null; extract_path:string|null; zip_exists:number; extracted:number; episode_count:number|null; size_bytes:number; status:PackageCacheStatus; last_used_at:string|null; last_error:string|null; created_at:string; updated_at:string; }
function map(r:CacheRow):PackageCacheRecord { return { cacheId:r.cache_id, cacheKey:r.cache_key, dramaId:r.drama_id, packageTaskId:r.package_task_id??undefined, packageObjectKey:r.package_object_key??undefined, packageName:r.package_name, deviceId:r.device_id, zipPath:r.zip_path??undefined, extractPath:r.extract_path??undefined, zipExists:r.zip_exists===1, extracted:r.extracted===1, episodeCount:r.episode_count??undefined, sizeBytes:Number(r.size_bytes), status:r.status, lastUsedAt:r.last_used_at??undefined, lastError:r.last_error??undefined, createdAt:r.created_at, updatedAt:r.updated_at }; }
export class PackageCacheMysqlRepository {
  constructor(private readonly pool:Pool) {}
  async upsert(input: Omit<PackageCacheRecord,"cacheId"|"createdAt"|"updatedAt">):Promise<PackageCacheRecord> { await this.pool.execute(`INSERT INTO clip_package_cache (cache_key,drama_id,package_task_id,package_object_key,package_name,device_id,zip_path,extract_path,zip_exists,extracted,episode_count,size_bytes,status,last_used_at,last_error) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE package_task_id=VALUES(package_task_id),package_object_key=VALUES(package_object_key),package_name=VALUES(package_name),zip_path=VALUES(zip_path),extract_path=VALUES(extract_path),zip_exists=VALUES(zip_exists),extracted=VALUES(extracted),episode_count=VALUES(episode_count),size_bytes=VALUES(size_bytes),status=VALUES(status),last_used_at=VALUES(last_used_at),last_error=VALUES(last_error)`,[input.cacheKey,input.dramaId,input.packageTaskId??null,input.packageObjectKey??null,input.packageName,input.deviceId,input.zipPath??null,input.extractPath??null,input.zipExists?1:0,input.extracted?1:0,input.episodeCount??null,input.sizeBytes,input.status,input.lastUsedAt?toMysqlDate(input.lastUsedAt):null,input.lastError??null]); const [rows]=await this.pool.query<CacheRow[]>(`SELECT * FROM clip_package_cache WHERE cache_key=? AND device_id=? LIMIT 1`,[input.cacheKey,input.deviceId]); return map(rows[0]!); }
  async listPage(input:{dramaId?:string;deviceId?:string;status?:string;limit:number;offset:number}):Promise<{items:PackageCacheRecord[];total:number}> { const where:string[]=[];const p:(string|number)[]=[];if(input.dramaId){where.push("drama_id=?");p.push(input.dramaId);}if(input.deviceId){where.push("device_id=?");p.push(input.deviceId);}if(input.status){where.push("status=?");p.push(input.status);}const w=where.length?` WHERE ${where.join(" AND ")}`:"";const [c]=await this.pool.query<RowDataPacket[]>(`SELECT COUNT(*) cnt FROM clip_package_cache${w}`,p);const [rows]=await this.pool.query<CacheRow[]>(`SELECT * FROM clip_package_cache${w} ORDER BY updated_at DESC LIMIT ? OFFSET ?`,[...p,input.limit,input.offset]);return {items:rows.map(map),total:Number(c[0]?.cnt??0)}; }
  async event(cacheId:number,type:string,detail?:unknown):Promise<void>{await this.pool.execute("INSERT INTO clip_package_cache_event (cache_id,event_type,detail_json) VALUES (?,?,?)",[cacheId,type,detail?JSON.stringify(detail):null]);}
}
